
name: CI
on:
  branch
  push:
    branches: [ "android-r" ]
  pull_request:
    branches: [ "android-r" ]
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    - name: depend
       run: |
          apt update
          apt install python bash sed wget git curl zip tar expect make cmake automake autoconf bison perl gperf gawk flex bc  zstd openssl libcurl4-openssl-dev
    - name: unzip aospclang
       run: apt install aria2c aria2 && aria2c https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master.tar.gz && tar -xzvf master.tar.gz -C clang
   -name: install clang
     run: cd clang/clang-r450784e/ && /bin/cp -rf ./bin /bin && /bin/cp -rf ./lib64 /lib
   -name: clang version
     run: clang -v
   -name:add env to repo
     run: |
          git add * && git commit -m "hi" &&  git branch hi && git checkout hi && git push origin hi
                  
